---
# tasks file for backend-migrate

- name: Generate App Key
  shell: |
      cd {{ backend_dir }}
      php artisan key:generate
  become: true

- name: Generate App Key 2
  command:
    cmd: "php artisan migrate"
    chdir: "{{ backend_dir }}"

- name: Generate JWT Secret
  command:
    cmd: "php artisan jwt:secret"
    chdir: "{{ backend_dir }}"