---
- name: Main Playbook
  hosts: all
  become: true

  vars_files:
    - ../env/vars.yml

- import_playbook: prepare.yml

- import_playbook: build.yml

- import_playbook: migrate.yml

- import_playbook: deploy.yml
